package grpc

import (
	"fmt"
	"os"
	"sync"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/dynamicpb"
)

// Transcoder handles JSON-to-protobuf and protobuf-to-JSON transcoding
// using proto file descriptors for proper message type resolution.
type Transcoder struct {
	mu    sync.RWMutex
	files *protoregistry.Files

	// loaded tracks whether descriptors have been loaded
	loaded bool
}

// NewTranscoder creates a new Transcoder instance.
func NewTranscoder() *Transcoder {
	return &Transcoder{
		files: new(protoregistry.Files),
	}
}

// LoadDescriptors loads compiled proto descriptors from a .desc file
// (a serialized FileDescriptorSet generated by protoc --descriptor_set_out).
func (t *Transcoder) LoadDescriptors(path string) error {
	// #nosec G304 -- proto descriptor path is configured by the administrator.
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read descriptor file %q: %w", path, err)
	}

	fds := &descriptorpb.FileDescriptorSet{}
	if err := proto.Unmarshal(data, fds); err != nil {
		return fmt.Errorf("failed to unmarshal descriptor set: %w", err)
	}

	t.mu.Lock()
	defer t.mu.Unlock()

	for _, fdProto := range fds.GetFile() {
		fd, err := protodesc.NewFile(fdProto, t.files)
		if err != nil {
			return fmt.Errorf("failed to create file descriptor for %q: %w", fdProto.GetName(), err)
		}
		if _, err := t.files.FindFileByPath(fd.Path()); err != nil {
			// Only register if not already registered.
			if regErr := t.files.RegisterFile(fd); regErr != nil {
				return fmt.Errorf("failed to register file descriptor %q: %w", fd.Path(), regErr)
			}
		}
	}

	t.loaded = true
	return nil
}

// IsLoaded reports whether descriptors have been successfully loaded.
func (t *Transcoder) IsLoaded() bool {
	t.mu.RLock()
	defer t.mu.RUnlock()
	return t.loaded
}

// JSONToProto converts a JSON payload to a serialized protobuf message.
// The method parameter should be a fully-qualified gRPC method path like
// "/package.ServiceName/MethodName".
func (t *Transcoder) JSONToProto(method string, jsonData []byte) ([]byte, error) {
	t.mu.RLock()
	defer t.mu.RUnlock()

	if !t.loaded {
		return nil, fmt.Errorf("transcoder: proto descriptors not loaded; call LoadDescriptors before transcoding")
	}

	inputDesc, err := t.resolveInputType(method)
	if err != nil {
		return nil, err
	}

	msg := dynamicpb.NewMessage(inputDesc)
	if err := protojson.Unmarshal(jsonData, msg); err != nil {
		return nil, fmt.Errorf("transcoder: failed to unmarshal JSON to proto: %w", err)
	}

	out, err := proto.Marshal(msg)
	if err != nil {
		return nil, fmt.Errorf("transcoder: failed to marshal proto: %w", err)
	}
	return out, nil
}

// ProtoToJSON converts a serialized protobuf message to JSON.
// The method parameter should be a fully-qualified gRPC method path like
// "/package.ServiceName/MethodName".
func (t *Transcoder) ProtoToJSON(method string, protoData []byte) ([]byte, error) {
	t.mu.RLock()
	defer t.mu.RUnlock()

	if !t.loaded {
		return nil, fmt.Errorf("transcoder: proto descriptors not loaded; call LoadDescriptors before transcoding")
	}

	outputDesc, err := t.resolveOutputType(method)
	if err != nil {
		return nil, err
	}

	msg := dynamicpb.NewMessage(outputDesc)
	if err := proto.Unmarshal(protoData, msg); err != nil {
		return nil, fmt.Errorf("transcoder: failed to unmarshal proto data: %w", err)
	}

	opts := protojson.MarshalOptions{
		EmitUnpopulated: true,
	}
	out, err := opts.Marshal(msg)
	if err != nil {
		return nil, fmt.Errorf("transcoder: failed to marshal proto to JSON: %w", err)
	}
	return out, nil
}

// resolveInputType finds the input message descriptor for a gRPC method.
func (t *Transcoder) resolveInputType(method string) (protoreflect.MessageDescriptor, error) {
	md, err := t.resolveMethod(method)
	if err != nil {
		return nil, err
	}
	return md.Input(), nil
}

// resolveOutputType finds the output message descriptor for a gRPC method.
func (t *Transcoder) resolveOutputType(method string) (protoreflect.MessageDescriptor, error) {
	md, err := t.resolveMethod(method)
	if err != nil {
		return nil, err
	}
	return md.Output(), nil
}

// resolveMethod finds the method descriptor for a fully-qualified gRPC method path.
// Expected format: "/package.ServiceName/MethodName"
func (t *Transcoder) resolveMethod(method string) (protoreflect.MethodDescriptor, error) {
	serviceName, methodName, err := parseGRPCMethod(method)
	if err != nil {
		return nil, err
	}

	// Find the service descriptor by iterating registered files.
	var found protoreflect.MethodDescriptor
	t.files.RangeFiles(func(fd protoreflect.FileDescriptor) bool {
		services := fd.Services()
		for i := 0; i < services.Len(); i++ {
			svc := services.Get(i)
			if string(svc.FullName()) == serviceName {
				md := svc.Methods().ByName(protoreflect.Name(methodName))
				if md != nil {
					found = md
					return false // stop iteration
				}
			}
		}
		return true // continue
	})

	if found == nil {
		return nil, fmt.Errorf("transcoder: method %q not found in loaded descriptors", method)
	}
	return found, nil
}

// parseGRPCMethod parses a gRPC method path like "/package.Service/Method"
// and returns the full service name and method name.
func parseGRPCMethod(method string) (service, rpcMethod string, err error) {
	// Strip leading slash
	if len(method) > 0 && method[0] == '/' {
		method = method[1:]
	}

	// Find the separator between service and method
	idx := 0
	for i := len(method) - 1; i >= 0; i-- {
		if method[i] == '/' {
			idx = i
			break
		}
	}

	if idx == 0 || idx == len(method)-1 {
		return "", "", fmt.Errorf("transcoder: invalid gRPC method path %q; expected format /package.Service/Method", "/"+method)
	}

	return method[:idx], method[idx+1:], nil
}
