apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apicerberus

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - ingress.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: apicerberus
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/apicerberus/apicerberus
    newTag: latest
