apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: apicerberus
  namespace: apicerberus
  labels:
    app.kubernetes.io/name: apicerberus
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apicerberus
      app.kubernetes.io/component: gateway
